### ISSUE TITLE
Comparisons to NeRFace

### ISSUE THREAD

**Issue by gafniguy** [USTC3DV/NeRFBlendShape-code#1]
Hi,

Congrats on the paper! 

Watching the videos I'm curious about the flickering in nerface, could it be that you don't freeze the latent codes during inference?

**Comment by XuanGhahahaha** [comment]
Hi,

Thank you for your interest in our paper.

We have freezed the latent codes during inference. According to our experiments, flickering sometimes occured in videos with exaggerated expressions and large head rotations. It seems there is no obvious flickering for normal talking situation.

**Comment by gafniguy** [comment]
Cool, thanks!
