### ISSUE TITLE
What's the method used to segment the front face?

### ISSUE THREAD

**Issue by chenerg** [USTC3DV/NeRFBlendShape-code#13]
The segmented face in your video is smooth and accurate, however when I segment the face using [face-parsing.PyTorch](https://github.com/zllrunning/face-parsing.PyTorch), the result is flicking.

**Comment by XuanGhahahaha** [comment]
We also used this method for segmentation. Although there will be a little noise and flicking in segmented face images, NeRF tends to synthesize a denoised result when training is finished.

**Comment by chenerg** [comment]
That's amazing! Thanks!
