### ISSUE TITLE
Question about Equ. 9 of the paper

### ISSUE THREAD

**Issue by flyingshan** [USTC3DV/NeRFBlendShape-code#14]
Hi! I am confused of the Equ. 9 of the paper, where the equation is about how to update the density grid. 
According to the equation, for each expression basis, we compute a new multi-resolution hashtable h^i. My question is: what is the relationship between the newly computed hashtable h^i and the density grid? Are they equivalent? If not, how to update the density grid according to h^i?
Looking forward to your reply!

**Comment by XuanGhahahaha** [comment]
Hi,  the newly computed hashtable and density grid are different, the hash table is same as what is used in instant-ngp, which is a compact multi-resolution structure, the density grid is an $N \times N \times N$ grid, which is used to store the density distribution of a NeRF(corresponding to a specific expression).

In our implementation, we query the grid voxel centers in this hash table $\hat{h_i}$ and use MLP to interpret queried features to density corresponding to grid voxels. You could read line 445 in https://github.com/ashawkey/torch-ngp/blob/main/nerf/renderer.py for more details.

Once you got density grids corresponding to all $\hat{h_i}$, you could compute element-wise maximum to merge them to get a final density grid for ray marching

**Comment by flyingshan** [comment]
Got it! Thank you
