### ISSUE TITLE
What is the meaning of the parameter 'index'?

### ISSUE THREAD

**Issue by peibinchen** [USTC3DV/NeRFBlendShape-code#16]
Hi,
Thanks for your opensource code. I'm curious about the 'index' parameter at https://github.com/USTC3DV/NeRFBlendShape-code/blob/main/nerf/network_tcnn.py#L106 and https://github.com/USTC3DV/NeRFBlendShape-code/blob/main/nerf/renderer.py#L147. How is it used when training?
Thanks.

**Comment by peibinchen** [comment]
Also, how is the 'exp_ori' used in the forward function of the network when training?

**Comment by XuanGhahahaha** [comment]
Hi, both variables are not used in our final training code any more. I forget to delete them in this inference code.

**Comment by peibinchen** [comment]
@XuanGhahahaha Thanks for your kindly response. I have two another questions.
(1)  https://github.com/USTC3DV/NeRFBlendShape-code/blob/main/nerf/renderer.py#L152 I find that 'A' is used when training. How is it used? 
(2) What is the number of rays when training?  That is, what is the num_rays in https://github.com/USTC3DV/NeRFBlendShape-code/blob/20265159e5/nerf/utils.py#L62 when training?

**Comment by XuanGhahahaha** [comment]
_A_ is the alpha value used for mask supervision.  _num_rays_ is 1024.
