### ISSUE TITLE
[Render] What is the difference of the codes between NeRFBlendShape-code and ngp?

### ISSUE THREAD

**Issue by peibinchen** [USTC3DV/NeRFBlendShape-code#17]
Hi,
I notice that the render codes of NeRFBlendshape-code is slightly different from that of ngp. Can I directly use the render codes in ngp to train and test the NeRFBlendshape model?

**Comment by XuanGhahahaha** [comment]
Hi,
It will be ok if you adopt torch-ngp to reimplement our project. Our main modifications in torch-ngp are on hash encoding, density grid updating, and the training strategy. However our code is developed on the basis of an early verison of torch-ngp. So I am not sure if it could work without any changes in code.

**Comment by peibinchen** [comment]
@XuanGhahahaha  Thanks for your comments.  Is the [density grid updating] in your paper implemented in the gridencoder.cu?

**Comment by XuanGhahahaha** [comment]
It is not included in this inference code. You could implement it by yourself on the basis of torch-ngp. Maybe the discussion in #14 could help you.
