### ISSUE TITLE
数据集没有声音

### ISSUE THREAD

**Issue by 821029883** [USTC3DV/NeRFBlendShape-code#2]
作者您好，感谢您即将开源的出色工作！
您存放在谷歌网盘上的视频数据集没有声音，请问是否提供音频？

**Comment by XuanGhahahaha** [comment]
您好，感谢对我们工作的关注！
数据一部分是我们自己拍的，一部分是来自于其他工作公开的数据，我们自己拍的数据里其实很多时候只是做了表情，并没有发出声音。如果是需要一些演讲和谈话的视频的话，可以参考Neural Voice Puppetry(https://justusthies.github.io/posts/neural-voice-puppetry/) 和SSP-NeRF(https://alvinliu0.github.io/projects/SSP-NeRF) 从youtube上收集的数据集。我们的实验里很多数据也来自于这两个工作收集的数据集。

**Comment by 821029883** [comment]
好的，感谢(O(∩_∩)O)
