### ISSUE TITLE
TypeError: _composite_raysBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 0

### ISSUE THREAD

**Issue by Tara8573** [USTC3DV/NeRFBlendShape-code#20]
Thank you for your wonderful work！
I ran the inference code and got this error.
```
depth, image,exps_code = _run(rays_o, rays_d,exps,exp_ori, bound, num_steps, bg_color) 
File "....../NeRFBlendShape/nerf/renderer.py", line 130, in run_cuda
raymarching.composite_rays(n_alive, n_step, rays_alive[i % 2], rays_t[i % 2], sigmas, rgbs, deltas, weights_sum, depth, image)
TypeError: _composite_raysBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 0

```
https://github.com/USTC3DV/NeRFBlendShape-code/blob/d198ac270b9994e36d7ef86003777a2c1976ca7a/raymarching/raymarching.py#L66
It seems that the "forward" function lacks "return XXX". Could you give me some suggestions？Thank you so much！！！

**Comment by XuanGhahahaha** [comment]
Hi, this rendering part comes from an early version of torch-ngp so there may exist compatibility problem. Maybe the implementation in [Line 351 of torch-ngp's raymarching](https://github.com/ashawkey/torch-ngp/blob/main/raymarching/raymarching.py) could help you. I guess perhaps you only need to add `return tuple()` in the last line.

**Comment by Tara8573** [comment]
It works！！！Thanks~(￣▽￣)~*
