### ISSUE TITLE
What is the definition of the 47 blendshapes?

### ISSUE THREAD

**Issue by peibinchen** [USTC3DV/NeRFBlendShape-code#22]
Hi,
I wonder the definition of each dimension in your blendshape. Where can I find that?
Thanks.

**Comment by XuanGhahahaha** [comment]
Hi,
It is consistent with FaceWarehouse. Maybe this list could help you. 
https://github.com/deepmo24/CPEM/blob/main/assets/blendshape_name.md

**Comment by peibinchen** [comment]
Thanks!
