### ISSUE TITLE
Question about density grid

### ISSUE THREAD

**Issue by zhiyu-z** [USTC3DV/NeRFBlendShape-code#23]
Can you explain more about how to use the density grid when training. I get bad result when I reproduce the paper (I use density grid code in torch-ngp).

**Comment by josh-zhu** [comment]
needs help too. According to Equ. 9  of the paper,I try to pass an expression tensor [1,0,..,0,max_per_i,0,...,0], (where max_per_i is the i th element in max_per data) to the Network density function to get the sigma value of each grid corresponding to the i th expression basis h^i. But it seems to be incorrect. The mean density shrinks after iteration

**Comment by XuanGhahahaha** [comment]
I also implement the density grid update on the basis of torch-ngp. 

The first update occurs after about 1000 iterations, in which time the coarse geometry has been formed. Then the update is executed every 2000 iterations.
 
For detatiled computation, you could see #8 .

**Comment by zhiyu-z** [comment]
Thanks for your kindly replay!
