### ISSUE TITLE
meaning of min_46 max_46.txt 

### ISSUE THREAD

**Issue by cucdengjunli** [USTC3DV/NeRFBlendShape-code#24]
Hi 
thanks for your great work!
Is it the range of expression coefficients? and how do you get it ?
Is it necessary for training or inference?

**Comment by XuanGhahahaha** [comment]
Hi, It is the range of expression coefficients, It is computed by element-wise maximum/minimum of expressions in train set.
It could restrict the range of tested expressions coefficients to avoid some artifacts and also be used for our expression aware density grid update.
