### ISSUE TITLE
Confusion about the background of the picture

### ISSUE THREAD

**Issue by BCL123456-BAL** [USTC3DV/NeRFBlendShape-code#25]
This is really a great job.

I have some small confusion, but I cannot verify myself due to the limitation of data set and equipment. I hope you can help me solve the confusion.

The backgrounds of the figures in the data are all solid colors, whether this is to reduce the computational amount of reconstruction, or because the manipulation of the head will affect the background area, such as distortion.

**Comment by XuanGhahahaha** [comment]
Hi, thanks for your interest in our work.

Actually we use a extracted static background image for each training. But in inference, we just set the background to white for convenience. We use AD-NeRF's implementation to extract the background https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L122
