### ISSUE TITLE
Discussion of camera error

### ISSUE THREAD

**Issue by BCL123456-BAL** [USTC3DV/NeRFBlendShape-code#26]
You mentioned in the limitation of your paper that The camera parameters and input conditions are important for NeRF based techniques. Large errors in tracking may cause losing details in our constructed model.

So why not add a learnable code like Nerface to the MLP along with the position code and expression coefficient to compensate for errors in facial expression and posture estimation

![image](https://user-images.githubusercontent.com/75575496/230768761-9605136c-d27b-4299-a9b8-c1f1e898605a.png)

**Comment by XuanGhahahaha** [comment]
This may be a right direction to reduce the infuence of tracking errors. But we found that, at least in limited 20 minutes, directly concatenating a learnable code do not benefit the training a lot. That's why we didn't use this strategy in our final solution.

**Comment by BCL123456-BAL** [comment]
Thank you for your advice
