### ISSUE TITLE
About using a new video as dataset

### ISSUE THREAD

**Issue by BerryKanry114514** [USTC3DV/NeRFBlendShape-code#29]
Hi!
Thanks for your great work!

I've done testing the network with the provided training dataset and I have received amazing performance.
But I wonder, if I want to use a new video, for example, a video of myself, how can I get those expression coefficients, like in the max_46.txt, min_46.txt, as well as the transforms.json?

**Comment by BerryKanry114514** [comment]
Also, since I want to train a new video, I found that the training part of the code is missing? There's only codes for "normal_test".

**Comment by XuanGhahahaha** [comment]
Hi, thanks for your interest on our work.

Unfortuanately because this work was finished when I were intern at Image Derivative Inc. Training code and tracking code will not be released.
