### ISSUE TITLE
How to extract mesh?

### ISSUE THREAD

**Issue by YiChenCityU** [USTC3DV/NeRFBlendShape-code#33]
Hi, I want to know if we can get mesh from this kind of method?

**Comment by XuanGhahahaha** [comment]
Hi, similar to EG3D, we extract the iso-surface of density field with [PyMCubes](https://github.com/pmneila/PyMCubes).

**Comment by YiChenCityU** [comment]
Thanks, I have tried use density_grid to extract mesh. But the quality is not good. Is there any possible to add sdf to it(like neus)? Does the encoder support  second derivative?

**Comment by XuanGhahahaha** [comment]
The second derivative is not supported in our code. You may need to implement it in grid encoder.
