### ISSUE TITLE
The dataset you provided are corrupted. Some data are missing.

### ISSUE THREAD

**Issue by YiChenCityU** [USTC3DV/NeRFBlendShape-code#34]

**Comment by XuanGhahahaha** [comment]
Sorry, it seems some images are lost, I have uploaded a new version. Could you please try again?

Thank you!

**Comment by YiChenCityU** [comment]
The dataset is OK. Thanks very much.

**Comment by XuanGhahahaha** [comment]
My pleasure, thank you for pointing out this!
