### ISSUE TITLE
Question about expression-aware density grid update strategy

### ISSUE THREAD

**Issue by Dong142857** [USTC3DV/NeRFBlendShape-code#8]
Hi,Thanks for your amazing work! I am confused with the expression-aware stragy in your paper: Does the 'h' mean the hash table or the density grid? If it is hash table, how to get the density grid using new hash table?
![image](https://user-images.githubusercontent.com/47628302/208244336-8b648169-dd1f-4d37-a041-61ae19750685.png)

**Comment by XuanGhahahaha** [comment]
Hi! 
Thanks for your interest in our work. 
'h' here represents the hash table. We query the grid voxel centers in this hash table and use MLP to interpret queried features to density corresponding to grid voxels.
You could read line 445 in https://github.com/ashawkey/torch-ngp/blob/main/nerf/renderer.py for more details

**Comment by Dong142857** [comment]
Thanks for your kind reply!
